# Usage:
#     SECRET_KEY='mysecretkey' ALLOWED_HOSTS='*' docker-compose -f docker-compose.prod.yml up --build -d
#
# where ALLOWED_HOSTS is a space-separated list of hostnames (or "*")
version: '3.7'

services:
  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build: .
    image: lis_gis-django:1
    environment:
      ALLOWED_HOSTS:
      DEBUG: '0'
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      SECRET_KEY:
      STATIC_URL: /static/
    depends_on:
      - db
    command: ["sh", "-c", "gunicorn --bind 0.0.0.0:8000 lis_germplasm.wsgi"]
    
  db:
    build:
      context: postgres
