# development
version: '3.7'

services:
  web:
    build: .
    environment:
      SECRET_KEY: secret_key
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      STATIC_URL: /static/
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["sh", "-c", "sleep 10 && python3 manage.py runserver 0.0.0.0:8000"]
    
  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - ./docker-entrypoint-initdb.d/z-peanutbase.sql.gz:/docker-entrypoint-initdb.d/z-peanutbase.sql.gz
