# development
version: '3.7'

services:
  web:
    build: .
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '1'
      SECRET_KEY: secret_key
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      STATIC_URL: /static/
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["sh", "-c", "sleep 5 && python3 manage.py runserver 0.0.0.0:8000"]

  db:
    build:
      context: postgres
