# development
version: '2.3'

services:
  web:
    build: .
    environment:
      ALLOWED_HOSTS: '*'
      DEBUG: '1'
      SECRET_KEY: secret_key
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      STATIC_URL: /static/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["sh", "-c", "sleep 5 && python3 manage.py runserver 0.0.0.0:8000"]

  db:
    build: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres -h 127.0.0.1 || exit 1"
      retries: 10
