# local or remote production deployment
# Usage:
#     POSTGRES_PASSWORD='mypassword' ALLOWED_HOSTS='myhost.mydomain' docker-compose -f docker-compose.prod.yml up --build -d
#
# where ALLOWED_HOSTS is a space-separated list of hostnames (or "*")
version: '3.7'

services:
  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build: .
    image: lis_gis-django:1
    environment:
      ALLOWED_HOSTS:
      #DEBUG: ''
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: postgres
      PGDATABASE: postgres
      STATIC_URL: /static/
    depends_on:
      - db
    
  db:
    build:
      context: postgres
    environment:
      POSTGRES_PASSWORD:
