# local development deployment
version: '2.3'

services:
  web:
    build:
      context: .
      target: dev
    environment:
      DEBUG: '1'
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      STATIC_URL: /static/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: true
      - type: volume
        target: /app/grin_app/static/grin_app/js/node_modules

  db:
    build: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres -h 127.0.0.1 || exit 1"
      retries: 10
